/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ejrjMDsDD0y
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Loader2 } from "lucide-react";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

interface TopupProps {
  handleAmount: (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => void;
  handleTopUp: () => void;
  loading: boolean;
  currentBalance: number;
  amount: number | null;
}

export function Topup({
  handleAmount,
  handleTopUp,
  loading,
  currentBalance,
  amount,
}: TopupProps) {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <CardTitle>Top-Up Account</CardTitle>
        <CardDescription>
          Enter the amount to top-up your account.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="currentBalance">Current Balance</Label>
          <Input
            disabled
            id="currentBalance"
            placeholder="Enter current balance"
            type="number"
            value={currentBalance}
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="topUp">Top-Up Amount</Label>
          <Input
            id="topUp"
            placeholder="Enter amount to top-up"
            type="number"
            onChange={handleAmount}
            value={amount ?? ""}
          />
        </div>
      </CardContent>
      <CardFooter>
        {loading ? (
          <Button disabled>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Loading...
          </Button>
        ) : (
          <Button className="ml-auto" onClick={handleTopUp}>
            Top-Up
          </Button>
        )}
      </CardFooter>
    </Card>
  );
}
