// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -source=transaction.go -destination=./mock/transaction.go
//
// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	v4 "github.com/labstack/echo/v4"
	domain "github.com/ryuji-cre8ive/super-metro/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionUsecase is a mock of TransactionUsecase interface.
type MockTransactionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionUsecaseMockRecorder
}

// MockTransactionUsecaseMockRecorder is the mock recorder for MockTransactionUsecase.
type MockTransactionUsecaseMockRecorder struct {
	mock *MockTransactionUsecase
}

// NewMockTransactionUsecase creates a new mock instance.
func NewMockTransactionUsecase(ctrl *gomock.Controller) *MockTransactionUsecase {
	mock := &MockTransactionUsecase{ctrl: ctrl}
	mock.recorder = &MockTransactionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionUsecase) EXPECT() *MockTransactionUsecaseMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTransactionUsecase) Add(c v4.Context, userId, paymentId, transactionType string, amount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", c, userId, paymentId, transactionType, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTransactionUsecaseMockRecorder) Add(c, userId, paymentId, transactionType, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTransactionUsecase)(nil).Add), c, userId, paymentId, transactionType, amount)
}

// Get mocks base method.
func (m *MockTransactionUsecase) Get(c v4.Context, userId string) ([]*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", c, userId)
	ret0, _ := ret[0].([]*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTransactionUsecaseMockRecorder) Get(c, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTransactionUsecase)(nil).Get), c, userId)
}
